# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('r', models.ManyToManyField(to='cmdb.Hosts')),
            ],
        ),
    ]
